[package]
name = "multiplayer-fps"
version = "0.1.0"
edition = "2021"
rust-version = "1.74"
default-run = "client"

[dependencies]
macroquad = "=0.4.13"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winuser"] }

[[bin]]
name = "client"
path = "src/bin/client.rs"

[[bin]]
name = "server"
path = "src/bin/server.rs"
